submodules/btcpayserver/BTCPayServer/Models/WalletViewModels/ListWalletsViewModel.cs
using System.Collections.Generic;
using BTCPayServer;
using NBitcoin;

namespace BTCPayServer.Models.WalletViewModels
{
    public class ListWalletsViewModel
    {
        public class WalletViewModel
        {
            public string StoreName { get; set; }
            public string StoreId { get; set; }
            public string CryptoCode { get; set; }
            public string Balance { get; set; }
            public WalletId Id { get; set; }
        }

        public Dictionary<BTCPayNetwork, IMoney> BalanceForCryptoCode { get; set; } = new Dictionary<BTCPayNetwork, IMoney>();
        public List<WalletViewModel> Wallets { get; set; } = new List<WalletViewModel>();
    }
}

submodules/btcpayserver/BTCPayServer/Models/WalletViewModels/SignWithSeedViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using NBitcoin;

namespace BTCPayServer.Models.WalletViewModels
{
    public class SignWithSeedViewModel : IHasBackAndReturnUrl
    {
        public SigningContextModel SigningContext { get; set; } = new SigningContextModel();

        [Required]
        [Display(Name = "BIP39 Seed (12/24 word mnemonic phrase) or HD private key (xprv...)")]
        public string SeedOrKey { get; set; }

        [Display(Name = "Optional seed passphrase")]
        public string Passphrase { get; set; }

        public string BackUrl { get; set; }
        public string ReturnUrl { get; set; }

        public ExtKey GetExtKey(Network network)
        {
            ExtKey extKey = null;
            try
            {
                var mnemonic = new Mnemonic(SeedOrKey);
                extKey = mnemonic.DeriveExtKey(Passphrase);
            }
            catch (Exception)
            {
            }

            if (extKey == null)
            {
                try
                {
                    extKey = ExtKey.Parse(SeedOrKey, network);
                }
                catch (Exception)
                {
                }
            }
            return extKey;
        }
    }
}

submodules/btcpayserver/BTCPayServer/Models/WalletViewModels/WalletBumpFeeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using NBitcoin;
using static BTCPayServer.Models.WalletViewModels.WalletBumpFeeViewModel;

namespace BTCPayServer.Models.WalletViewModels
{
    public class WalletBumpFeeViewModel
    {
        public string ReturnUrl { get; set; }
        [Display(Name = "Transaction Id")]
        public uint256 TransactionId { get; set; }
        public List<SelectListItem> BumpFeeMethods { get; set; } = new();
        public string[] Outpoints { get; set; }
        public string[] TransactionHashes { get; set; }
        public List<WalletSendModel.FeeRateOption> RecommendedSatoshiPerByte { get; set; }
        [Display]
        public decimal? FeeSatoshiPerByte { get; set; }
        [Display]
        public decimal? CurrentFeeSatoshiPerByte { get; set; }
        public bool IsMultiSigOnServer { get; set; }
        [Display(Name = "Fee bump method")]
        public string BumpMethod { get; set; }

        public string Command { get; set; }
#nullable enable
        public record BumpTarget(HashSet<OutPoint> Outpoints, HashSet<uint256> TxIds)
        {

            public uint256? GetSingleTransactionId()
                => this switch
                {
                    { TxIds: { Count: 1 } ids, Outpoints: { Count: 0 } } => ids.First(),
                    { TxIds: { Count: 0 }, Outpoints: { Count: 1 } outpoints } => outpoints.First().Hash,
                    _ => null
                };
            public HashSet<uint256> GetTransactionIds()
            => (TxIds.Concat(Outpoints.Select(o => o.Hash))).ToHashSet();

            public BumpTarget Filter(HashSet<uint256> elligibleTxs)
            => new BumpTarget(
                    Outpoints.Where(o => elligibleTxs.Contains(o.Hash)).ToHashSet(),
                    TxIds.Where(t => elligibleTxs.Contains(t)).ToHashSet());

            public List<OutPoint> GetMatchedOutpoints(IEnumerable<OutPoint> outpoints)
            {
                List<OutPoint> matches = new();
                HashSet<uint256> bumpedTxs = new();
                foreach (var outpoint in outpoints)
                {
                    if (Outpoints.Contains(outpoint))
                    {
                        matches.Add(outpoint);
                        bumpedTxs.Add(outpoint.Hash);
                    }
                    else if (TxIds.Contains(outpoint.Hash) && bumpedTxs.Add(outpoint.Hash))
                    {
                        matches.Add(outpoint);
                    }
                }
                return matches;
            }
        }

        public BumpTarget GetBumpTarget()
        {
            if (TransactionId is not null)
                return new BumpTarget(new(), new([TransactionId]));
            HashSet<OutPoint> outpoints = new();
            HashSet<uint256> txids = new();
            foreach (var o in Outpoints ?? [])
            {
                try
                {
                    outpoints.Add(OutPoint.Parse(o));
                }
                catch { }
            }
            foreach (var o in TransactionHashes ?? [])
            {
                try
                {
                    txids.Add(uint256.Parse(o));
                }
                catch { }
            }
            return new BumpTarget(outpoints, txids);
        }
#nullable restore
    }
}

submodules/btcpayserver/BTCPayServer/Controllers/UIWalletsController.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Abstractions.Models;
using BTCPayServer.BIP78.Sender;
using BTCPayServer.Client;
using BTCPayServer.Client.Models;
using BTCPayServer.Data;
using BTCPayServer.HostedServices;
using BTCPayServer.ModelBinders;
using BTCPayServer.Models;
using BTCPayServer.Models.WalletViewModels;
using BTCPayServer.Payments;
using BTCPayServer.Payments.Bitcoin;
using BTCPayServer.Payments.PayJoin;
using BTCPayServer.Payouts;
using BTCPayServer.Rating;
using BTCPayServer.Services;
using BTCPayServer.Services.Invoices;
using BTCPayServer.Services.Labels;
using BTCPayServer.Services.Rates;
using BTCPayServer.Services.Stores;
using BTCPayServer.Services.Wallets;
using BTCPayServer.Services.Wallets.Export;
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using NBitcoin;
using NBXplorer;
using NBXplorer.DerivationStrategy;
using NBXplorer.Models;
using Newtonsoft.Json;
using static BTCPayServer.Models.WalletViewModels.WalletBumpFeeViewModel;
using StoreData = BTCPayServer.Data.StoreData;

namespace BTCPayServer.Controllers
{
    [Route("wallets")]
    [Authorize(Policy = Policies.CanModifyStoreSettings, AuthenticationSchemes = AuthenticationSchemes.Cookie)]
    [AutoValidateAntiforgeryToken]
    //16mb psbts
    [RequestFormLimits(ValueLengthLimit = FormReader.DefaultValueLengthLimit * 4)]
    public partial class UIWalletsController : Controller
    {
        private StoreRepository Repository { get; }
        private WalletRepository WalletRepository { get; }
        private BTCPayNetworkProvider NetworkProvider { get; }
        private ExplorerClientProvider ExplorerClientProvider { get; }
        private IServiceProvider ServiceProvider { get; }
        private RateFetcher RateFetcher { get; }
        private IStringLocalizer StringLocalizer { get; }

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly NBXplorerDashboard _dashboard;
        private readonly IAuthorizationService _authorizationService;
        private readonly IFeeProviderFactory _feeRateProvider;
        private readonly BTCPayWalletProvider _walletProvider;
        private readonly WalletReceiveService _walletReceiveService;
        private readonly SettingsRepository _settingsRepository;
        private readonly DelayedTransactionBroadcaster _broadcaster;
        private readonly PayjoinClient _payjoinClient;
        private readonly LabelService _labelService;
        private readonly PaymentMethodHandlerDictionary _handlers;
        private readonly DefaultRulesCollection _defaultRules;
        private readonly Dictionary<PaymentMethodId, ICheckoutModelExtension> _paymentModelExtensions;
        private readonly TransactionLinkProviders _transactionLinkProviders;
        private readonly InvoiceRepository _invoiceRepository;
        private readonly PullPaymentHostedService _pullPaymentHostedService;
        private readonly WalletHistogramService _walletHistogramService;

        private readonly PendingTransactionService _pendingTransactionService;
        readonly CurrencyNameTable _currencyTable;
        private readonly DisplayFormatter _displayFormatter;

        public UIWalletsController(
            PendingTransactionService pendingTransactionService,
            StoreRepository repo,
            WalletRepository walletRepository,
            CurrencyNameTable currencyTable,
            BTCPayNetworkProvider networkProvider,
            UserManager<ApplicationUser> userManager,
            NBXplorerDashboard dashboard,
            WalletHistogramService walletHistogramService,
            RateFetcher rateProvider,
            IAuthorizationService authorizationService,
            ExplorerClientProvider explorerProvider,
            IFeeProviderFactory feeRateProvider,
            BTCPayWalletProvider walletProvider,
            WalletReceiveService walletReceiveService,
            SettingsRepository settingsRepository,
            DelayedTransactionBroadcaster broadcaster,
            PayjoinClient payjoinClient,
            IServiceProvider serviceProvider,
            PullPaymentHostedService pullPaymentHostedService,
            LabelService labelService,
            DefaultRulesCollection defaultRules,
            PaymentMethodHandlerDictionary handlers,
            Dictionary<PaymentMethodId, ICheckoutModelExtension> paymentModelExtensions,
            IStringLocalizer stringLocalizer,
            TransactionLinkProviders transactionLinkProviders,
            InvoiceRepository invoiceRepository,
            DisplayFormatter displayFormatter)
        {
            _pendingTransactionService = pendingTransactionService;
            _currencyTable = currencyTable;
            _labelService = labelService;
            _defaultRules = defaultRules;
            _handlers = handlers;
            _paymentModelExtensions = paymentModelExtensions;
            _transactionLinkProviders = transactionLinkProviders;
            _invoiceRepository = invoiceRepository;
            Repository = repo;
            WalletRepository = walletRepository;
            RateFetcher = rateProvider;
            _authorizationService = authorizationService;
            NetworkProvider = networkProvider;
            _userManager = userManager;
            _dashboard = dashboard;
            ExplorerClientProvider = explorerProvider;
            _feeRateProvider = feeRateProvider;
            _walletProvider = walletProvider;
            _walletReceiveService = walletReceiveService;
            _settingsRepository = settingsRepository;
            _broadcaster = broadcaster;
            _payjoinClient = payjoinClient;
            _pullPaymentHostedService = pullPaymentHostedService;
            ServiceProvider = serviceProvider;
            _walletHistogramService = walletHistogramService;
            StringLocalizer = stringLocalizer;
            _displayFormatter = displayFormatter;
        }

        [HttpGet("{walletId}/pending/{pendingTransactionId}/cancel")]
        public IActionResult CancelPendingTransaction(
            [ModelBinder(typeof(WalletIdModelBinder))] WalletId walletId,
            string pendingTransactionId)
        {
            return View("Confirm", new ConfirmModel("Abort Pending Transaction",
                "Proceeding with this action will invalidate Pending Transaction and all accepted signatures.",
                "Confirm Abort"));
        }
        [HttpPost("{walletId}/pending/{pendingTransactionId}/cancel")]
        public async Task<IActionResult> CancelPendingTransactionConfirmed(
            [ModelBinder(typeof(WalletIdModelBinder))] WalletId walletId,
            string pendingTransactionId)
        {
            await _pendingTransactionService.CancelPendingTransaction(GetPendingTxId(walletId, pendingTransactionId));
            TempData.SetStatusMessageModel(new StatusMessageModel()
            {
                Severity = StatusMessageModel.StatusSeverity.Success,
                Message = $"Aborted Pending Transaction {pendingTransactionId}"
            });
            return RedirectToAction(nameof(WalletTransactions), new { walletId = walletId.ToString() });
        }


        [HttpGet("{walletId}/pending/{pendingTransactionId}")]
        public async Task<IActionResult> ViewPendingTransaction(
            [ModelBinder(typeof(WalletIdModelBinder))] WalletId walletId,
            string pendingTransactionId)
        {
            var network = NetworkProvider.GetNetwork<BTCPayNetwork>(walletId.CryptoCode);
            var pendingTransaction =
                await _pendingTransactionService.GetPendingTransaction(GetPendingTxId(walletId, pendingTransactionId));
            if (pendingTransaction is null)
                return NotFound();
            var blob = pendingTransaction.GetBlob();
            if (blob?.PSBT is null)
                return NotFound();
            var currentPsbt = PSBT.Parse(blob.PSBT, network.NBitcoinNetwork);
            foreach (CollectedSignature collectedSignature in blob.CollectedSignatures)
            {
                var psbt = PSBT.Parse(collectedSignature.ReceivedPSBT, network.NBitcoinNetwork);
                currentPsbt = currentPsbt.Combine(psbt);
            }

            var derivationSchemeSettings = GetDerivationSchemeSettings(walletId);

            var vm = new WalletPSBTViewModel()
            {
                CryptoCode = network.CryptoCode,
                SigningContext = new SigningContextModel(currentPsbt)
                {
                    PendingTransactionId = pendingTransactionId,
                    PSBT = currentPsbt.ToBase64(),
                },
            };
            await FetchTransactionDetails(walletId, derivationSchemeSettings, vm, network);
            await vm.GetPSBT(network.NBitcoinNetwork, ModelState);
            return View("WalletPSBTDecoded", vm);
        }

        private PendingTransactionService.PendingTransactionFullId GetPendingTxId(WalletId walletId, string pendingTransactionId)
        => new (walletId.CryptoCode, walletId.StoreId, pendingTransactionId);


        [Route("{walletId}/transactions/bump")]
        [Route("{walletId}/transactions/{transactionId}/bump")]
        public async Task<IActionResult> WalletBumpFee([ModelBinder(typeof(WalletIdModelBinder))]
            [FromQuery]
            WalletId walletId,
            WalletBumpFeeViewModel model,
          CancellationToken cancellationToken = default)
        {

submodules/btcpayserver/BTCPayServer/Views/UIWallets/ListWallets.cshtml
@using BTCPayServer.Client
@model BTCPayServer.Models.WalletViewModels.ListWalletsViewModel
@{
    ViewData.SetActivePage(WalletsNavPages.Index, StringLocalizer["Wallets"]);
}

<partial name="_StatusMessage" />

<div class="d-sm-flex justify-content-between mb-2">
    <h2 class="mb-0">
        @ViewData["Title"]
        <small>
            <a href="https://docs.btcpayserver.org/Wallet/" target="_blank" rel="noreferrer noopener" title="@StringLocalizer["More information..."]">
                <vc:icon symbol="info" />
            </a>
        </small>
    </h2>
    @if (Model.Wallets.Any())
    {
        <div class="mt-2 mt-sm-1">
            @foreach (var balance in Model.BalanceForCryptoCode)
            {
                <div class="fs-5 fw-semibold">@($"{balance.Value.ShowMoney(balance.Key)} {balance.Key.CryptoCode}")</div>
            }
            <div class="text-muted text-sm-end fs-6" text-translate="true">Total Balance</div>
        </div>
    }
</div>
<div class="row">
    <div class="col-lg-12">
        @if (Model.Wallets.Any())
        {
            <div class="table-responsive-md">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th text-translate="true">Store Name</th>
                        <th text-translate="true">Crypto Code</th>
                        <th text-translate="true">Balance</th>
                        <th text-translate="true" class="text-end">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var wallet in Model.Wallets)
                    {
                    <tr>

                        <td>
                            <a
                                permission="@Policies.CanModifyStoreSettings"
                                asp-action="GeneralSettings" asp-controller="UIStores" asp-route-storeId="@wallet.StoreId">
                                @wallet.StoreName
                            </a>
                            <span not-permission="@Policies.CanModifyStoreSettings">@wallet.StoreName</span>
                        </td>

                        <td>@wallet.CryptoCode</td>
                        <td><span permission="@Policies.CanModifyStoreSettings">@wallet.Balance</span></td>
                        <td class="text-end">
                            <a asp-action="WalletTransactions" asp-route-walletId="@wallet.Id" text-translate="true">Manage</a>
                        </td>
                    </tr>
                    }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <p class="text-secondary mt-3" text-translate="true">
                There are no wallets yet. You can add wallets in the store setup.
            </p>
        }
    </div>
</div>

submodules/btcpayserver/BTCPayServer/Views/UIWallets/SigningContext.cshtml
@model BTCPayServer.Models.WalletViewModels.SigningContextModel

@if (Model != null)
{
    <input type="hidden" asp-for="PSBT" value="@Model.PSBT"/>
    <input type="hidden" asp-for="OriginalPSBT" value="@Model.OriginalPSBT"/>
    <input type="hidden" asp-for="PayJoinBIP21" value="@Model.PayJoinBIP21"/>
    <input type="hidden" asp-for="EnforceLowR" value="@Model.EnforceLowR" />
    <input type="hidden" asp-for="ChangeAddress"  value="@Model.ChangeAddress" />
    <input type="hidden" asp-for="PendingTransactionId"  value="@Model.PendingTransactionId" />
	<input type="hidden" asp-for="BalanceChangeFromReplacement" value="@Model.BalanceChangeFromReplacement" />
}

submodules/btcpayserver/BTCPayServer/Views/UIWallets/WalletPSBTCombine.cshtml
@using BTCPayServer.Controllers
@model WalletPSBTCombineViewModel
@{
    var walletId = Context.GetRouteValue("walletId").ToString();
	Model.ReturnUrl ??= Url.WalletTransactions(walletId);
    Layout = "_LayoutWizard";
    ViewData.SetActivePage(WalletsNavPages.PSBT, StringLocalizer["Combine PSBT"], walletId);
}

@section Navbar {
	<partial name="_BackAndReturn" model="Model" />
}

<header class="text-center">
    <h1>@ViewData["Title"]</h1>
</header>

<form class="form-group" method="post" asp-action="WalletPSBTCombine" asp-route-walletId="@Context.GetRouteValue("walletId")" enctype="multipart/form-data">
    <input type="hidden" asp-for="OtherPSBT"/>
    <input type="hidden" asp-for="ReturnUrl" />
        <input type="hidden" asp-for="BackUrl" />
    <div class="form-group">
        <label asp-for="PSBT" class="form-label"></label>
        <textarea class="form-control" rows="5" asp-for="PSBT"></textarea>
        <span asp-validation-for="PSBT" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="UploadedPSBTFile" class="form-label"></label>
        <input type="file" class="form-control" asp-for="UploadedPSBTFile">
    </div>
    <button id="Submit" type="submit" class="btn btn-primary" text-translate="true">Combine</button>
</form>

submodules/btcpayserver/BTCPayServer/Views/UIWallets/WalletReceive.cshtml
@inject BTCPayServerEnvironment env
@using BTCPayServer.Controllers
@using BTCPayServer.Components.QRCode
@using BTCPayServer.Services
@model BTCPayServer.Controllers.WalletReceiveViewModel
@{
    var walletId = Context.GetRouteValue("walletId").ToString();
    var returnUrl = Model.ReturnUrl ?? Url.Action(nameof(UIWalletsController.WalletTransactions), new { walletId });
    Layout = "_LayoutWizard";
    ViewData.SetActivePage(WalletsNavPages.Receive, StringLocalizer["Receive {0}", Model.CryptoCode], walletId);
}

@section PageHeadContent
{
    <link href="~/main/qrcode.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/vendor/tom-select/tom-select.bootstrap5.min.css" asp-append-version="true" rel="stylesheet">
    <script src="~/vendor/tom-select/tom-select.complete.min.js" asp-append-version="true"></script>
}

@section Navbar {
	<a href="@Url.EnsureLocal(returnUrl, Context.Request)" id="CancelWizard" class="cancel">
        <vc:icon symbol="cross" />
    </a>
}

<header class="text-center">
    <h1 class="mb-4">@ViewData["Title"]</h1>
</header>

<form method="post" asp-action="WalletReceive">
    <input type="hidden" asp-for="ReturnUrl" />
    @if (string.IsNullOrEmpty(Model.Address))
    {
        <div class="payment-box mb-3">
            <button id="generateButton" class="btn btn-primary w-100" type="submit" name="command" value="generate-new-address">Generate next available @Model.CryptoCode address</button>
        </div>
    }
    else
    {
        <noscript>
            <div class="form-group">
                <input type="text" class="form-control " readonly="readonly" asp-for="Address" id="address"/>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" readonly="readonly" asp-for="PaymentLink" id="payment-link"/>
            </div>
            <div class="row mt-4">
                <button type="submit" name="command" value="generate-new-address" class="btn btn-primary w-100" text-translate="true">Generate another address</button>
            </div>
        </noscript>
        <div class="nav flex-wrap align-items-center justify-content-center gap-2 mb-4">
            <a class="btcpay-pill active" data-bs-toggle="tab" href="#address-tab" text-translate="true">Address</a>
            <a class="btcpay-pill " data-bs-toggle="tab" href="#link-tab" text-translate="true">Link</a>
        </div>
        <div class="only-for-js col-sm-10 col-xxl-8 mx-auto" id="app">
            <div class="tab-content text-center">
                <div class="tab-pane payment-box" id="link-tab" role="tabpanel">
                    <div class="qr-container clipboard-button" data-clipboard="@Model.PaymentLink">
                        <vc:qr-code data="@Model.PaymentLink"/>
						@if (Model.CryptoImage is not null)
						{
							<img src="@Model.CryptoImage" class="qr-icon" alt="@Model.CryptoCode"/>
						}
					</div>
                    <div class="input-group mt-3">
                        <div class="form-floating">
                            <vc:truncate-center text="@Model.PaymentLink" padding="15" elastic="true" classes="form-control-plaintext" id="PaymentLink" />
                            <label for="PaymentLink" text-translate="true">Payment Link</label>
                        </div>
                    </div>
                </div>
                <div class="tab-pane payment-box show active" id="address-tab" role="tabpanel">
                    <div class="qr-container clipboard-button" data-clipboard="@Model.Address">
                        <vc:qr-code data="@Model.Address"/>
						@if (Model.CryptoImage is not null)
						{
							<img src="@Model.CryptoImage" class="qr-icon" alt="@Model.CryptoCode"/>
						}
					</div>
                    <div class="input-group mt-3">
                        <div class="form-floating">
                            <vc:truncate-center text="@Model.Address" padding="15" elastic="true" classes="form-control-plaintext" id="Address" />
                            <label for="Address" text-translate="true">Address</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="payment-box">
            <div class="my-3">
                <div class="input-group">
                    <div class="form-floating">
                        <vc:label-manager selected-labels="Model.SelectedLabels" wallet-object-id="new WalletObjectId(WalletId.Parse(walletId), WalletObjectData.Types.Address, Model.Address)" />
                        <label text-translate="true">Labels</label>
                    </div>
                </div>
            </div>
            <div class="mt-4">
                <button type="submit" name="command" value="generate-new-address" class="btn btn-primary w-100" text-translate="true">Generate another address</button>
            </div>
            <div class="payment-box mt-3">
                <a class="btn btn-outline-info w-100"
                   id="reserved-addresses-button"
                   asp-controller="UIWallets" asp-action="ReservedAddresses" asp-route-walletId="@walletId">
                    Reserved Addresses
                </a>
            </div>


        </div>
    }
    @if (env.CheatMode)
    {
        <div class="payment-box mt-3">
            <button type="submit" name="command" value="fill-wallet" class="btn btn-outline-info w-100" text-translate="true">Cheat Mode: Send funds to this wallet</button>
        </div>
    }
</form>

submodules/btcpayserver/BTCPayServer/Views/UIWallets/WalletSendVault.cshtml
@using BTCPayServer.Blazor.VaultBridge
@using BTCPayServer.Hosting
@model WalletSendVaultModel
@{
    var walletId = Context.GetRouteValue("walletId")?.ToString() ?? "";
	Model.ReturnUrl ??= Url.WalletTransactions(walletId);
    Layout = "_LayoutWizard";
    ViewData.SetActivePage(WalletsNavPages.Send, StringLocalizer["Sign the transaction"], walletId);
    this.ViewData.SetBlazorAllowed(true);

    // Calculate maximum PSBT size accounting for SignalR message overhead
    var blazorMax = Startup.BlazorMaximumReceiveMessageSize;
    var otherDataSize = 500; // Estimated overhead for other SignalR message data
    decimal waste = 1.35m; // Base64 re-encoding overhead factor (approximately 35%)
    long maxPSBTSize = (long)((blazorMax - otherDataSize) / waste);
}

@section Navbar {
	<partial name="_BackAndReturn" model="Model" />
}

<header class="text-center">
    <h1>@ViewData["Title"]</h1>
    <p class="lead text-secondary mt-3" text-translate="true">Using BTCPay Server Vault</p>
</header>

<partial name="_StatusMessage" />

@if (maxPSBTSize >= Model.SigningContext.PSBT.Length)
{
    <div class="row mt-5 mb-4">
        <div class="col-md-8 mx-auto">
            <component type="typeof(VaultBridgeUI)"
                       param-Controller="@(new SignHWIController()
                                         {
                                             StoreId = WalletId.Parse(walletId).StoreId,
                                             CryptoCode = WalletId.Parse(walletId).CryptoCode,
                                             PSBT = Convert.FromBase64String(Model.SigningContext.PSBT)
                                         })"
                       render-mode="Server" />
        </div>
    </div>
}
else
{
    <div class="alert alert-danger my-4" role="alert">
        <span>@StringLocalizer["PSBT too large to be signed by Vault. (Max: {0} bytes)", maxPSBTSize]</span>
    </div>
}

<div id="body" class="my-4">
    <form id="broadcastForm" asp-action="WalletSendVault" asp-route-walletId="@walletId" method="post" style="display:none;">
        <input type="hidden" id="WalletId" asp-for="WalletId" />
        <input type="hidden" asp-for="ReturnUrl" />
        <input type="hidden" asp-for="BackUrl" />
        <partial name="SigningContext" for="SigningContext" />
    </form>
</div>


@section PageFootContent
{
    <script src="~/js/vaultbridge.js" asp-append-version="true"></script>
    <script>
        vault.setSignedPSBT = function (data)
        {
            $("#SigningContext_PSBT").val(data.psbt);
            $("#broadcastForm").submit();
        }
    </script>
}