submodules/btcpayserver/BTCPayServer/Models/ManageViewModels/GenerateRecoveryCodesViewModel.cs
namespace BTCPayServer.Models.ManageViewModels
{
    public class GenerateRecoveryCodesViewModel
    {
        public string[] RecoveryCodes { get; set; }
    }
}

submodules/btcpayserver/BTCPayServer/Controllers/UIHomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Contracts;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Client;
using BTCPayServer.Data;
using BTCPayServer.Filters;
using BTCPayServer.Models;
using BTCPayServer.Models.StoreViewModels;
using BTCPayServer.Services;
using BTCPayServer.Services.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BTCPayServer.Controllers
{
    public class UIHomeController : Controller
    {
        private readonly ThemeSettings _theme;
        private readonly StoreRepository _storeRepository;
        private IHttpClientFactory HttpClientFactory { get; }
        private SignInManager<ApplicationUser> SignInManager { get; }

        private IFileProvider _WebRootFileProvider;

        public LanguageService LanguageService { get; }

        public UIHomeController(IHttpClientFactory httpClientFactory,
                              ThemeSettings theme,
                              LanguageService languageService,
                              StoreRepository storeRepository,
                              IWebHostEnvironment environment,
                              SignInManager<ApplicationUser> signInManager)
        {
            _theme = theme;
            HttpClientFactory = httpClientFactory;
            LanguageService = languageService;
            _storeRepository = storeRepository;
            SignInManager = signInManager;
            _WebRootFileProvider = environment.WebRootFileProvider;
        }

        [HttpGet("home")]
        public Task<IActionResult> Home()
        {
            return Index();
        }

        [Route("")]
        [DomainMappingConstraint]
        public async Task<IActionResult> Index()
        {
            if (_theme.FirstRun)
            {
                return RedirectToAction(nameof(UIAccountController.Register), "UIAccount");
            }

            if (SignInManager.IsSignedIn(User))
            {
                var userId = SignInManager.UserManager.GetUserId(HttpContext.User);
                var storeId = HttpContext.GetUserPrefsCookie()?.CurrentStoreId;
                if (storeId != null)
                {
                    // verify store exists and redirect to it
                    var store = await _storeRepository.FindStore(storeId);
                    if (store != null)
                    {
                        return RedirectToAction(nameof(UIStoresController.Index), "UIStores", new { storeId });
                    }
                }

                var stores = await _storeRepository.GetStoresByUserId(userId!);
                var activeStore = stores.FirstOrDefault(s => !s.Archived);
                return activeStore != null
                    ? RedirectToAction(nameof(UIStoresController.Index), "UIStores", new { storeId = activeStore.Id })
                    : RedirectToAction(nameof(UIUserStoresController.CreateStore), "UIUserStores");
            }

            return Challenge();
        }

        [Route("misc/lang")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public IActionResult Languages()
        {
            return Json(LanguageService.GetLanguages(), new JsonSerializerSettings { Formatting = Formatting.Indented });
        }

        [Route("misc/permissions")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public IActionResult Permissions()
        {
            return Json(Client.Models.PermissionMetadata.PermissionNodes, new JsonSerializerSettings { Formatting = Formatting.Indented });
        }
        [Route("misc/translations/{resource}/{lang}")]
        [AllowAnonymous]
        public IActionResult GetTranslations(string resource, string lang)
        {
            string path;
            if (resource.StartsWith("checkout"))
                path = "locales/checkout";
            else
                return NotFound();
            var enLang = Lang(path + "/en.json");
            var en = (enLang as JsonResult)?.Value as JObject;
            if (en is null || lang == "en" || lang == "en-US")
                return enLang;
            lang = LanguageService.FindLanguage(lang)?.Code;
            if (lang is null)
                return enLang;
            var oLang = Lang(path + $"/{lang}.json");
            var o = (oLang as JsonResult)?.Value as JObject;
            if (o is null)
                return enLang;
            en.Merge(o);
            return Json(en);
        }

        private IActionResult Lang(string path)
        {
            var fi = _WebRootFileProvider.GetFileInfo(path);
            try
            {
                using var fs = fi.CreateReadStream();
                return Json(JObject.Load(new JsonTextReader(new StreamReader(fs, leaveOpen: true))));
            }
            catch
            {
                return NotFound();
            }
        }

        [Route("swagger/v1/swagger.json")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie + "," + AuthenticationSchemes.Greenfield)]
        public async Task<IActionResult> Swagger([FromServices] IEnumerable<ISwaggerProvider> swaggerProviders)
        {
            JObject json = new();
            var res = await Task.WhenAll(swaggerProviders.Select(provider => provider.Fetch()));
            foreach (JObject jObject in res)
            {
                json.Merge(jObject);
            }
            var servers = new JArray();
            servers.Add(new JObject(new JProperty("url", HttpContext.Request.GetAbsoluteRoot())));
            json["servers"] = servers;
            var tags = (JArray)json["tags"];
            json["tags"] = new JArray(tags
                .Select(o => (name: ((JObject)o)["name"].Value<string>(), o))
                .OrderBy(o => o.name)
                .Select(o => o.o)
                .ToArray());
            return Json(json);
        }

        [Route("docs")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
        public IActionResult SwaggerDocs()
        {
            return View();
        }

        [Route("recovery-seed-backup")]
        [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
        public IActionResult RecoverySeedBackup(RecoverySeedBackupViewModel vm)
        {
            return View("RecoverySeedBackup", vm);
        }

        [HttpPost]
        [Route("postredirect-callback-test")]
        public ActionResult PostRedirectCallbackTestpage(IFormCollection data)
        {
            var list = data.Keys.Aggregate(new Dictionary<string, string>(), (res, key) =>
            {
                res.Add(key, data[key]);
                return res;
            });
            return Json(list);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

submodules/btcpayserver/BTCPayServer/Controllers/UIManageController.cs
using System;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Contracts;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Client;
using BTCPayServer.Data;
using BTCPayServer.Events;
using BTCPayServer.Fido2;
using BTCPayServer.Models.ManageViewModels;
using BTCPayServer.Security.Greenfield;
using BTCPayServer.Services;
using BTCPayServer.Services.Mails;
using BTCPayServer.Services.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;

namespace BTCPayServer.Controllers
{
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanViewProfile)]
    [Route("account/{action:lowercase=Index}")]
    public partial class UIManageController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly EmailSenderFactory _EmailSenderFactory;
        private readonly ILogger _logger;
        private readonly UrlEncoder _urlEncoder;
        private readonly BTCPayServerEnvironment _btcPayServerEnvironment;
        private readonly APIKeyRepository _apiKeyRepository;
        private readonly IAuthorizationService _authorizationService;
        private readonly Fido2Service _fido2Service;
        private readonly CallbackGenerator _callbackGenerator;
        private readonly IHtmlHelper Html;
        private readonly UserService _userService;
        private readonly UriResolver _uriResolver;
        private readonly IFileService _fileService;
        private readonly EventAggregator _eventAggregator;
        readonly StoreRepository _StoreRepository;
        public IStringLocalizer StringLocalizer { get; }

        public UIManageController(
          UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager,
          EmailSenderFactory emailSenderFactory,
          ILogger<UIManageController> logger,
          UrlEncoder urlEncoder,
          StoreRepository storeRepository,
          BTCPayServerEnvironment btcPayServerEnvironment,
          APIKeyRepository apiKeyRepository,
          IAuthorizationService authorizationService,
          Fido2Service fido2Service,
          CallbackGenerator callbackGenerator,
          UserService userService,
          UriResolver uriResolver,
          IFileService fileService,
          IStringLocalizer stringLocalizer,
          IHtmlHelper htmlHelper,
          EventAggregator eventAggregator)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _EmailSenderFactory = emailSenderFactory;
            _logger = logger;
            _urlEncoder = urlEncoder;
            _btcPayServerEnvironment = btcPayServerEnvironment;
            _apiKeyRepository = apiKeyRepository;
            _authorizationService = authorizationService;
            _fido2Service = fido2Service;
            _callbackGenerator = callbackGenerator;
            Html = htmlHelper;
            _eventAggregator = eventAggregator;
            _userService = userService;
            _uriResolver = uriResolver;
            _fileService = fileService;
            _StoreRepository = storeRepository;
            StringLocalizer = stringLocalizer;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            var blob = user.GetBlob() ?? new();
            var model = new IndexViewModel
            {
                Email = user.Email,
                Name = blob.Name,
                ImageUrl = string.IsNullOrEmpty(blob.ImageUrl) ? null : await _uriResolver.Resolve(Request.GetAbsoluteRootUri(), UnresolvedUri.Create(blob.ImageUrl)),
                EmailConfirmed = user.EmailConfirmed,
                RequiresEmailConfirmation = user.RequiresEmailConfirmation
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DisableShowInvoiceStatusChangeHint()
        {

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var blob = user.GetBlob() ?? new();
            blob.ShowInvoiceStatusChangeHint = false;
            user.SetBlob(blob);
            await _userManager.UpdateAsync(user);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(IndexViewModel model, [FromForm] bool RemoveImageFile = false)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            bool needUpdate = false;
            var email = user.Email;
            if (model.Email != email)
            {
                if (!(await _userManager.FindByEmailAsync(model.Email) is null))
                {
                    TempData[WellKnownTempData.ErrorMessage] = StringLocalizer["The email address is already in use with an other account."].Value;
                    return RedirectToAction(nameof(Index));
                }
                var setUserResult = await _userManager.SetUserNameAsync(user, model.Email);
                if (!setUserResult.Succeeded)
                {
                    throw new ApplicationException($"Unexpected error occurred setting email for user with ID '{user.Id}'.");
                }
                var setEmailResult = await _userManager.SetEmailAsync(user, model.Email);
                if (!setEmailResult.Succeeded)
                {
                    throw new ApplicationException($"Unexpected error occurred setting email for user with ID '{user.Id}'.");
                }
                needUpdate = true;
            }

            var blob = user.GetBlob() ?? new();
            if (blob.Name != model.Name)
            {
                blob.Name = model.Name;
                needUpdate = true;
            }

            if (model.ImageFile != null)
            {
                var imageUpload = await _fileService.UploadImage(model.ImageFile, user.Id);
                if (!imageUpload.Success)
                    ModelState.AddModelError(nameof(model.ImageFile), imageUpload.Response);
                else
                {
                    try
                    {
                        var storedFile = imageUpload.StoredFile!;
                        var fileIdUri = new UnresolvedUri.FileIdUri(storedFile.Id);
                        blob.ImageUrl = fileIdUri.ToString();
                        needUpdate = true;
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError(nameof(model.ImageFile), $"Could not save image: {e.Message}");
                    }
                }
            }
            else if (RemoveImageFile && !string.IsNullOrEmpty(blob.ImageUrl))
            {
                blob.ImageUrl = null;
                needUpdate = true;
            }
            user.SetBlob(blob);
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (needUpdate && await _userManager.UpdateAsync(user) is { Succeeded: true })
            {
                _eventAggregator.Publish(new UserEvent.Updated(user));
                TempData[WellKnownTempData.SuccessMessage] = StringLocalizer["Your profile has been updated"].Value;
            }
            else
            {
                TempData[WellKnownTempData.ErrorMessage] = StringLocalizer["Error updating profile"].Value;
            }
            
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendVerificationEmail(IndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(Index), model);
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var callbackUrl = await _callbackGenerator.ForEmailConfirmation(user, Request);
            (await _EmailSenderFactory.GetEmailSender()).SendEmailConfirmation(user.GetMailboxAddress(), callbackUrl);
            TempData[WellKnownTempData.SuccessMessage] = StringLocalizer["Verification email sent. Please check your email."].Value;
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ChangePassword()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var hasPassword = await _userManager.HasPasswordAsync(user);
            if (!hasPassword)
            {
                return RedirectToAction(nameof(SetPassword));
            }

            var model = new ChangePasswordViewModel();
            return View(model);
        }

        [HttpPost]

submodules/btcpayserver/BTCPayServer/Views/UIManage/APIKeys.cshtml
@namespace BTCPayServer.Client
@using BTCPayServer.Abstractions.Models
@using BTCPayServer.Abstractions.TagHelpers
@using BTCPayServer.TagHelpers
@using Microsoft.AspNetCore.Html
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject Security.ContentSecurityPolicies Csp
@model BTCPayServer.Controllers.UIManageController.ApiKeysViewModel
@{
	ViewData.SetActivePage(ManageNavPages.APIKeys, StringLocalizer["API Keys"]);
	Csp.UnsafeEval();
}

<div class="sticky-header">
    <h2>@ViewData["Title"]</h2>
	<a id="page-primary" class="btn btn-primary" asp-action="AddApiKey">
        Generate Key
    </a>
</div>
<partial name="_StatusMessage" />
<div class="row">
    <div class="col-xl-10 col-xxl-constrain">
        <p>
            @ViewLocalizer["The {0} offers programmatic access to your instance. You can manage your BTCPay Server (e.g. stores, invoices, users) as well as automate workflows and integrations (see {1}). For that you need the API keys, which can be generated here. Find more information in the {2}.",
                Html.ActionLink(StringLocalizer["Greenfield API"], "SwaggerDocs", "UIHome", new { }, new { target = "_blank",  rel = "noreferrer noopener" }),
                new HtmlString($"<a href=\"https://docs.btcpayserver.org/Development/GreenFieldExample/\" target=\"_blank\" rel=\"noreferrer noopener\">{StringLocalizer["use case examples"]}</a>"),
                Html.ActionLink(StringLocalizer["API authentication docs"], "SwaggerDocs", "UIHome", null, null, "section/Authentication", new { }, new { target = "_blank",  rel = "noreferrer noopener" })]
        </p>

        @if (Model.ApiKeyDatas.Any())
        {
            <table class="table table-lg">
                <thead>
                    <tr>
                        <th text-translate="true">Label</th>
                        <th text-translate="true" class="w-125px">Key</th>
                        <th text-translate="true">Permissions</th>
                        <th class="actions-col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var index = 0;
                    }
                    @foreach (var keyData in Model.ApiKeyDatas)
                    {
                        <tr>
                            <td>@keyData.Label</td>
                            <td>
                                <code class="hide-when-js">@keyData.Id</code>
                                <button type="button" class="btn btn-link only-for-js p-0" data-reveal-btn text-translate="true">Reveal</button>
                                <div hidden class="gap-2 align-items-center">
                                    <code>@keyData.Id</code>
                                    <button type="button" class="btn btn-link d-flex p-0 clipboard-button" data-clipboard="@keyData.Id">
                                        <vc:icon symbol="actions-copy" />
                                    </button>
                                </div>
                            </td>
                            <td>
                                @{
                                    var permissions = keyData.GetBlob().Permissions;
                                }
                                @if (!permissions.Any())
                                {
                                    <span class="info-note text-warning">
                                        <vc:icon symbol="warning"/>
                                        <span text-translate="true">No permissions</span>
                                    </span>
                                }
                                else
                                {
                                    @foreach (var permission in Permission.ToPermissions(permissions).Select(c => c.ToString()).Distinct().ToArray())
                                    {
                                        <div><code class="text-break">@permission</code></div>
                                    }
                                }
                            </td>
                            <td>
                                <div class="d-flex align-items-center justify-content-end gap-1">
                                    <a asp-action="DeleteAPIKey" asp-route-id="@keyData.Id" asp-controller="UIManage" data-bs-toggle="modal" data-bs-target="#ConfirmModal" data-description="Any application using the API key <strong>@Html.Encode(keyData.Label ?? keyData.Id)</strong> will immediately lose access." data-confirm-input="DELETE" text-translate="true">Delete</a>
                                    <span>-</span>
                                    <button type="button" class="btn btn-link only-for-js p-0" data-qr="@index" text-translate="true">Show QR</button>
                                </div>
                            </td>
                        </tr>
                        index++;
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<partial name="_Confirm" model="@(new ConfirmModel("Delete API key", "Any application using the API key will immediately lose access.", "Delete"))" />

<partial name="ShowQR" />

@section PageHeadContent {
    <link href="~/vendor/vue-qrcode-reader/vue-qrcode-reader.css" rel="stylesheet" asp-append-version="true" />
}
@section PageFootContent {
    <script src="~/vendor/vuejs/vue.min.js" asp-append-version="true"></script>
    <script src="~/vendor/vue-qrcode/vue-qrcode.min.js" asp-append-version="true"></script>
    <script src="~/vendor/ur-registry/urlib.min.js" asp-append-version="true"></script>
    <script src="~/vendor/vue-qrcode-reader/VueQrcodeReader.umd.min.js" asp-append-version="true"></script>

    <script>
        delegate('click', '[data-reveal-btn]', e => {
            const $container = e.target.parentElement.querySelector('[hidden]')
            e.target.setAttribute('hidden', 'true')
            $container.removeAttribute('hidden')
            $container.classList.add('d-inline-flex')
        })
        document.addEventListener("DOMContentLoaded", function () {
            const apiKeys = @Safe.Json(Model.ApiKeyDatas.Select(data => new
                            {
                                ApiKey = data.Id,
                                Host = Context.Request.GetAbsoluteRoot()
                            }));
            const qrApp = initQRShow({ title: "API Key QR" });
            delegate("click", "button[data-qr]", e => {
                e.preventDefault();
                const { qr } = e.target.dataset;
                const data = apiKeys[qr];
                qrApp.showData(JSON.stringify(data));
            });
        });
    </script>
}

submodules/btcpayserver/BTCPayServer/Views/UIManage/ChangePassword.cshtml
@model ChangePasswordViewModel
@{
    ViewData.SetActivePage(ManageNavPages.ChangePassword, StringLocalizer["Change your password"]);
}

<form method="post">
    <div class="sticky-header">
        <h2>@ViewData["Title"]</h2>
		<button id="page-primary" type="submit" class="btn btn-primary">Update Password</button>
    </div>
    <partial name="_StatusMessage" />
    <div class="row">
        <div class="col-xl-8 col-xxl-constrain">
            @if (!ViewContext.ModelState.IsValid)
            {
                <div asp-validation-summary="All"></div>
            }
            <div class="form-group">
                <label asp-for="OldPassword" class="form-label" data-required></label>
                <input asp-for="OldPassword" class="form-control"/>
                <span asp-validation-for="OldPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewPassword" class="form-label" data-required></label>
                <input asp-for="NewPassword" class="form-control"/>
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="form-label" data-required></label>
                <input asp-for="ConfirmPassword" class="form-control"/>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
        </div>
    </div>
</form>

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
}

submodules/btcpayserver/BTCPayServer/Views/UIManage/ConfirmAPIKey.cshtml
@model BTCPayServer.Controllers.UIManageController.AuthorizeApiKeysViewModel

@{
    var displayName = Model.ApplicationName ?? Model.ApplicationIdentifier;
    ViewData["Title"] = $"Authorize {displayName ?? "Application"}";
    Layout = "_LayoutWizard";
}

@section PageFootContent {
    <script>
        delegate('click', '#back', () => { history.back() });
    </script>
}

<form method="post" asp-controller="UIManage" asp-action="AuthorizeAPIKey">
    <input type="hidden" asp-for="ApplicationName" value="@Model.ApplicationName"/>
    <input type="hidden" asp-for="ApplicationIdentifier" value="@Model.ApplicationIdentifier"/>
    <input type="hidden" asp-for="ApiKey" value="@Model.ApiKey"/>
    <input type="hidden" asp-for="Strict" value="@Model.Strict"/>
    <input type="hidden" asp-for="RedirectUrl" value="@Model.RedirectUrl"/>
    <input type="hidden" asp-for="Permissions" value="@Model.Permissions"/>
    <input type="hidden" asp-for="SelectiveStores" value="@Model.SelectiveStores"/>
    <header class="text-center">
        <h1>@ViewData["Title"]</h1>
        <p class="lead text-secondary mt-3">Are you sure about exposing your API Key to @displayName?</p>
    </header>
    <p>
        You've previously generated the API Key <code>@Model.ApiKey</code> specifically for
        <strong>@displayName</strong> with the URL <code>@Model.RedirectUrl</code>.
    </p>
    <div class="d-flex gap-3">
        <button class="btn btn-primary" name="command" id="continue" type="submit" value="Confirm" text-translate="true">Authorize app</button>
        <button class="btn btn-secondary" name="command" id="back" type="button" text-translate="true">Cancel</button>
    </div>
</form>

submodules/btcpayserver/BTCPayServer/Views/UIManage/GenerateRecoveryCodes.cshtml
@model GenerateRecoveryCodesViewModel
@{
    ViewData.SetActivePage(ManageNavPages.TwoFactorAuthentication, StringLocalizer["Recovery codes"]);
}

<h2 class="mb-2 mb-lg-3">@ViewData["Title"]</h2>
<partial name="_StatusMessage" />

<div class="alert alert-warning" role="alert">
    <h5>
        <vc:icon symbol="warning" />
        <span text-translate="true">Put these codes in a safe place</span>
    </h5>
    <p class="mb-0" text-translate="true">
        If you lose your device and don't have the recovery codes you will lose access to your account.
    </p>
</div>
<div class="row">
    <div class="col-md-12">
        @for(var row = 0; row < Model.RecoveryCodes.Length; row += 2)
        {
            <code>@Model.RecoveryCodes[row]</code><text>&nbsp;</text><code>@Model.RecoveryCodes[row + 1]</code><br />
        }
    </div>
</div>
<div class="row mt-4">
     <div class="col-md-12">
        <a asp-action="TwoFactorAuthentication" class="btn btn-primary" text-translate="true">I wrote down my recovery codes</a>
    </div>
</div>

submodules/btcpayserver/BTCPayServer/Views/UIManage/LoginCodes.cshtml
@inject UserManager<ApplicationUser> UserManager;
@{
    ViewData.SetActivePage(ManageNavPages.LoginCodes, StringLocalizer["Login Codes"]);
}

<div class="sticky-header">
    <h2>@ViewData["Title"]</h2>
</div>
<partial name="_StatusMessage" />
<p text-translate="true">Easily log into BTCPay Server on another device using a simple login code from an already authenticated device.</p>
<component type="typeof(BTCPayServer.Blazor.UserLoginCode)" render-mode="ServerPrerendered" param-UserId="@UserManager.GetUserId(User)" param-id="@("LoginCode")"/>

submodules/btcpayserver/BTCPayServer/Views/UIManage/SetPassword.cshtml
@model BTCPayServer.Models.ManageViewModels.SetPasswordViewModel
@{
    ViewData.SetActivePage(ManageNavPages.ChangePassword, StringLocalizer["Set your password"]);
}

<form method="post">
    <div class="sticky-header">
        <h2>@ViewData["Title"]</h2>
		<button id="page-primary" type="submit" class="btn btn-primary">Set Password</button>
    </div>
    <partial name="_StatusMessage" />

    <p class="text-info" text-translate="true">You do not have a local username/password for this site. Add a local account so you can log in without an external login.</p>
    <div class="row">
        <div class="col-md-6">
            @if (!ViewContext.ModelState.IsValid)
            {
                <div asp-validation-summary="All"></div>
            }
            <div class="form-group">
                <label asp-for="NewPassword" class="form-label"></label>
                <input asp-for="NewPassword" class="form-control" />
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="form-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
        </div>
    </div>
</form>

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
}